### ISSUE TITLE
Figure with multilingual figcaptions

### ISSUE THREAD

**Issue by etclub** [w3c/htmlwg#25]
Sorry if it is not the right place to raise this issue, since I cannot comment at https://github.com/w3c/html/issues/1540

I have some html page for multilingual readers.
So I want to add multilingual figcaptions for an image.
I don't what is the best way to deal with it, as the standard says a figure should contain only one figcaption.

**Comment by LJWatson** [comment]
What is the use case for wanting multi-lingual figcaptions?

**Comment by etclub** [comment]
Well, some scholar research publish requires that an image should be captioned with the mother language and English.
And I want to turn my research to web pages.

**Comment by LJWatson** [comment]
One approach would be to use two `<p>` elements inside the `<figcaption>`, like this:

```
<figcaption>
<p>Default caption</p>
<p lang=fr">French caption</p>
</figure>
```
The first caption would be in the same language as the primary content of the page (and so inherits the lang attribute from the `<html>` element. The second paragraph would be in the alternate languagee and would need its own lang attribute with the relevant code (I've used French as the example here).
